### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Slater-Victoroff** [mushyfruit/houdini-web-rendering-interface#1]
This is awesome! Super excited to play around with this. One thing I noticed though is that there's no license on the repo right now. Would you consider adding one? Maybe MIT or Apache or something? Would love to contribute.

**Comment by mushyfruit** [comment]
Hey Slater, 

Thanks for taking a look at this project! I've gone ahead and added a MIT license to the repo.

I will be closing this issue now but feel free to open another if you run into any other issues. Excited to see what you might contribute!
